### PR TITLE
Add Java 8 Bouncy Castle based verification of RSA-OAEP SHA-2 vectors

### PR DESCRIPTION
**Pull request by collisdigital**
See /docs/development/custom-vectors/rsa-oaep-sha2.rst for instructions on how to build and run. 

Tested against all vectors in /vectors/cryptography_vectors/asymmetric/RSA/oaep-custom/ and passed successfully on OSX 10.11.3.

### CODE REVIEW

**Comment by collisdigital** [comment]
@reaperhulk Apologies if this isn't the right way to submit this, I'm not that familiar with the pull request process across forks like we have here! Let me know if anything needs changing etc.

**Comment by collisdigital** [comment]
Output should look like this:

```
> ...
> Verifying OAEP with mgf1_hash: SHA512 alg_hash: SHA512 - 256 bytes ciphertext - 16 bytes plaintext
> Verifying OAEP with mgf1_hash: SHA512 alg_hash: SHA512 - 256 bytes ciphertext - 26 bytes plaintext
> Verifying OAEP with mgf1_hash: SHA512 alg_hash: SHA512 - 256 bytes ciphertext - 36 bytes plaintext
> Verifying OAEP with mgf1_hash: SHA512 alg_hash: SHA512 - 256 bytes ciphertext - 23 bytes plaintext
> Verifying OAEP with mgf1_hash: SHA512 alg_hash: SHA512 - 256 bytes ciphertext - 45 bytes plaintext
> Verifying oaep-sha512-sha512.txt completed successfully.
> All verification completed successfully
```

**Comment by collisdigital** [comment]
If you change the mgf1_hash or alg_hash to something wrong you will get (to prove it does fail!) something like this:

```java
javax.crypto.BadPaddingException: data hash wrong
Verification Failed!
	at org.bouncycastle.jcajce.provider.asymmetric.rsa.CipherSpi.engineDoFinal(Unknown Source)
	at javax.crypto.Cipher.doFinal(Cipher.java:2165)
	at Verify_RSA_OAEP_SHA2.testDecrypt(Verify_RSA_OAEP_SHA2.java:333)
	at Verify_RSA_OAEP_SHA2.main(Verify_RSA_OAEP_SHA2.java:372)
```

**Comment by reaperhulk** [comment]
Thanks @collisdigital I'll take a look at this soon. I'm traveling tomorrow but should have time to look Wednesday.

**Comment by collisdigital** [comment]
Great, let me know if you have any issues.

**Comment by reaperhulk** [comment]
Verified this. Thanks for the docs on how to build this, they were very easy to follow. I'm going to go ahead and merge this into my PR and then update for a few style fixes. At that point we should be able to review/land these vectors. After that we can put in a PR to enable support for alternate hash algorithms on OpenSSL 1.0.2+!

**Comment by collisdigital** [comment]
👍 thanks!

**Comment by reaperhulk** [comment]
One extra item @collisdigital, I added some headers to the beginning of each file and the java code doesn't currently handle them properly. Do you have time for a quick fix? (You can see them in the latest PR update)

```
# RSA OAEP SHA2 vectors built for https://github.com/pyca/cryptography
# # Derived from the NIST OAEP SHA1 vectors.
# # Verified against the Bouncy Castle OAEP SHA2 implementation
#
```

**Comment by collisdigital** [comment]
Looking now....

**Comment by collisdigital** [comment]
@reaperhulk See https://github.com/reaperhulk/cryptography/pull/5

**Pull request merged**
